export const members = [
  {
    id: 1,
    name: "Pijus Dinda",
    domain: "Cybersecurity Analyst & Pen Tester",
    desc: "Every vulnerability is an opportunity to grow",
    image: "https://res.cloudinary.com/dflelt85r/image/upload/v1759721106/pijush_bwnttg.jpg",
    linkedin: "https://www.linkedin.com/in/pijus0101/",
    github: "https://github.com/Piku74",
    instagram: "#",
    gender: "male"
  },
  {
    id: 2,
    name: "Sukanya Mahapatra",
    domain: "Frontend Engineer & DSA Enthusiast",
    desc: "Perfection may be a dream, but progress is the real achievement",
    image: "https://res.cloudinary.com/dflelt85r/image/upload/v1759677968/sukanya_mdj28m.jpg",
    linkedin: "https://www.linkedin.com/in/sukanya9733/",
    github: "https://github.com/Sukanya9-0",
    instagram: "https://www.instagram.com/mahapatra_sukanya/",
    gender: "female"
  },
  {
    id: 3,
    name: "Kalyan Manna",
    domain: "Full Stack Developer",
    desc: "If your WHY is strong, the HOW becomes easy",
    image: "https://res.cloudinary.com/dflelt85r/image/upload/v1759677758/kalyan_lvhu1a.jpg",
    linkedin: "https://www.linkedin.com/in/kalyan-manna/",
    github: "https://github.com/Kalyan-github-4",
    instagram: "https://www.instagram.com/k_spidey_404?igsh=MTU4Mmo2Zmw0NXJ6ZQ==",
    gender: "male"
  },
  {
    id: 4,
    name: "Riya Bera",
    domain: "Frontend Developer",
    desc: "Be the CEO of your own life",
    image: "https://res.cloudinary.com/dflelt85r/image/upload/v1759721395/riya_vkonnc.jpg",
    linkedin: "https://www.linkedin.com/in/riya-bera-a22aa6356/",
    github: "https://github.com/Riya-2004-ctrl",
    instagram: "https://www.instagram.com/riyaa_bera_?igsh=MThud3h4eXdmMWhoOA==",
    gender: "female"
  },
  {
    id: 5,
    name: "Saptarshi Bisoi",
    domain: "MERN Stack Developer & Graphics Designer",
    desc: "Success is built on consistency, not motivation.",
    image: "https://res.cloudinary.com/dflelt85r/image/upload/v1760073552/saptarshi2_kyodrs.jpg",
    linkedin: "https://www.linkedin.com/in/saptarshi-legend/",
    github: " https://github.com/saptarshi-bisoi",
    instagram: "https://www.instagram.com/saptarshi.valid/",
    gender: "male"
  },
  {
    id: 6,
    name: "Moumita Maity",
    domain: "Full- Stack Web Developer ",
    desc: "Code with logic, design with purpose",
    image: "https://res.cloudinary.com/dflelt85r/image/upload/v1759677859/moumita_qywmm7.jpg",
    linkedin: "https://www.linkedin.com/in/moumita-maity-77bb2b375",
    github: "#",
    instagram: "https://www.instagram.com/moumita_maity2005?igsh=dm1iOHN5bjFuaHoy",
    gender: "female"
  },
  {
    id: 7,
    name: "Sathi Satvaya",
    domain: "Web Developer",
    desc: "Dream in code. Build in reality",
    image: "https://res.cloudinary.com/dflelt85r/image/upload/v1759677898/sathi_apj8gx.jpg",
    linkedin: " https://www.linkedin.com/in/sathi-satvaya-6710aa376",
    github: "#",
    instagram: "#",
    gender: "female"
  },
  {
    id: 8,
    name: "Anjan Mahata",
    domain: "Cyber Security Enthusiast",
    desc: "Your comfort zone is your enemy.",
    image: "https://res.cloudinary.com/dflelt85r/image/upload/v1759721110/anjan_jpsc2b.jpg",
    linkedin: "https://www.linkedin.com/in/anjan-mahata-a36844378?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    github: "https://github.com/AnjanMahata",
    instagram: "https://www.instagram.com/anjanmahata_?igsh=MWlnbDViNmkwMDd4cQ==",
    gender: "male"
  },
  {
    id: 9,
    name: "Sampathirao Gouthami",
    domain: "Full Stack Developer",
    linkedin: "https://www.linkedin.com/in/gouthami-sampathirao-b1b04936a?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    github: "https://github.com/sampathiraogouthami",
    instagram: "https://www.instagram.com/_itz_your_candy__?igsh=Mmc2czUwbWExbXRv",
    desc: "I’m not just made to stand out — I’m made to lead with beauty, brains, and bravery.",
    image:"https://res.cloudinary.com/dflelt85r/image/upload/v1759677782/gouthami_sqet7v.jpg",
    gender: "female"
  },
  {
    id: 10,
    name: "Anubhav Chowdhury ",
    domain: "Full-Stack Web Developer",
    linkedin: "https://www.linkedin.com/in/anubhav-chowdhury-b7905b339",
    github: "https://github.com/Anubhav-webdev",
    instagram: "#",
    desc: "LIFE is a journey, not a race. Enjoy every step",
    image:"https://res.cloudinary.com/dflelt85r/image/upload/v1759677827/anubhav_pic_josug6.webp",
    gender: "male"
  },
  {
    id: 11,
    name: "Satyajit Basanta",
    domain: "Ai & Ml Learner",
    linkedin: "http://linkedin.com/in/satyajit-basanta-3476ba363",
    github: "https://github.com/Avi-tech994",
    instagram: "https://www.instagram.com/satyajit_basanta?igsh=MXE3bGxvbmd2ZHR3cw==",
    desc: "AI is not about replacing humans — it’s about amplifying human potential",
    image:"https://res.cloudinary.com/dflelt85r/image/upload/v1759677940/satyajit_a7mglk.jpg",
    gender: "male"
  },
  {
    id: 12,
    name: "Angsuman Das",
    domain: "Cybersecurity Analyst & Pentesting",
    linkedin: "https://www.linkedin.com/in/angsuman-0xcc-8258322b7",
    github: "https://github.com/angsu0x90",
    instagram: "#",
    desc: "Lean your vulnerability to secure it",
    image:"https://res.cloudinary.com/dflelt85r/image/upload/v1760103339/angsuman_remzor.jpg",
    gender: "male"
  },
  {
    id: 13,
    name: "Falgune Mondal",
    domain: "Frontend Developer",
    linkedin: "https://www.linkedin.com/in/falgune-mondal-747b63255/",
    github: "https://github.com/falgune2701",
    instagram: "https://www.instagram.com/mondalbabu_2701/",
    desc: "Frontend is not just code, it's the face of your product",
    image:"https://res.cloudinary.com/dflelt85r/image/upload/v1759727311/falgune_2_lmdevi.jpg",
    gender: "male"
  },
  {
    id: 14,
    name: "Md Yousuf Mallik",
    domain: "Full stack & Android",
    linkedin: "https://www.linkedin.com/in/yousuf-mallik/",
    github: "https://github.com/Yousuf-cse",
    instagram: "https://www.instagram.com/404ineverything?igsh=aDZ3bjI5dXphN3Q2",
    desc: "The line between coding for pay and coding for passion separates good from great",
    image:"https://res.cloudinary.com/dxkje9whm/image/upload/v1758892593/yousuf_n1xsid.jpg",
    gender: "male"
  },
]
